config/routes.rb
Rails.application.routes.draw do
  
  resources :requests

  root 'static_pages#home'
  get 'static_pages/constitution'
  get 'static_pages/events'
  get 'static_pages/videos'  # The priority is based upon order of creation: first created -> highest priority.

end

app/models/request.rb
class Request < MailForm::Base
	attribute :name, :validate => true
	attribute :organization, :validate => true
	attribute :email, :validate => true
	attribute :phone, :validate => true
	attribute :address, :validate => true
	attribute :message, :validate => true
	attribute :comp, :validate => true
  def headers
    {
      :from => "ecsuaitplocker@gmail.com",
      :subject => "Computer Request",
      :to => "keroberts17@gmail.com",
      :cc => "aitp@my.easternct.edu",
      :cc => "citursa@easternct.edu",
    }
  end	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:show, :edit, :update, :destroy]

  # GET /requests
  # GET /requests.json
  def index
    @requests = Request.all
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
  end

  # GET /requests/new
  def new
    @request = Request.new
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(request_params)
    #@contact = Contact.new(params[:contact])
        @request.request = request
	    if @request.deliver
	          flash.now[:notice] = 'Thank you for your message. We will contact you soon!'
		  redirect_to 'http://ecsuaitp.com'
	      else
	          flash.now[:error] = 'Cannot send message.'
		  redirect_to 'http://ecsuaitp.com'
	    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to @request, notice: 'Request was successfully updated.' }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_url, notice: 'Request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params[:request]
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def constitution
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta charset='utf-8'>
  <meta name="description" content="The offical website of Eastern Connecticut State University's AITP Chapter">
  <meta name="keywords" content="aitp, web development, business, technology, BIS, computer science, eastern, connecticut, state, university">
  <meta name="author" content="Patrick Skiba, ECSU AITP">
  <title>AITP ECSU</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'static_pages/navbar' %>
<%= yield %>
<%= render 'static_pages/footer' %>
</body>
</html>

app/views/requests/_form.html.erb
<%= simple_form_for(@request) do |f| %>
  <%= f.error_notification %>
  <%= f.input :name %>
  <%= f.input :organization %>
  <%= f.input :email %>
  <%= f.input :phone %>
  <%= f.input :address %>
  <%= f.input :message %>
  <%= f.label :comp, 'Number of Computers Requested', :value => 'Number of Computers Requested ' %></br>
  <%= f.radio_button :comp, 1 %> 
  <%= f.label :comp, '1', :value => '1' %>
  <%= f.radio_button :comp, 2 %> 
  <%= f.label :comp, '2', :value => '2' %>
  <%= f.radio_button :comp, 3 %> 
  <%= f.label :comp, '3', :value => '3' %>
  <%= f.radio_button :comp, 4 %> 
  <%= f.label :comp, '4', :value => '4' %>
  <%= f.radio_button :comp, 5 %> 
  <%= f.label :comp, '5', :value => '5' %>
  <%= f.radio_button :comp, 6 %> 
  <%= f.label :comp, '6', :value => '6' %>
  <%= f.radio_button :comp, 7 %> 
  <%= f.label :comp, '7', :value => '7' %></br>
  <%= f.button :submit %>
<% end %>

app/views/requests/edit.html.erb
<h1>Editing Request</h1>

<%= render 'form' %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Requests</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
      <tr>
        <td><%= link_to 'Show', request %></td>
        <td><%= link_to 'Edit', edit_request_path(request) %></td>
        <td><%= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Request', new_request_path %>

app/views/requests/new.html.erb
</br>
<div class="container"> 
	<div class="row">
		<div class="col-lg-6" style="margin-left:25%">
			<h1>Computer Request Form</h1>
		</div>
	</div>
		<div class="col-lg-6" style="margin-left:25%">
			<%= render 'form' %>
		</div>
	</div>
</div>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_request_path(@request) %> |
<%= link_to 'Back', requests_path %>

app/views/static_pages/_footer.html.erb
	<!-- FOOTER -->
	<footer id="footer">
		<p>
			<div class="footer-links" style="padding-top:15px;">
				&copy; Patrick Skiba, Inc &middot; <%= link_to 'HOME', '/#home', class:"white-link" %>&middot;
    				<%= link_to 'ABOUT US', '/#about', class:"white-link" %>&middot;
    				<%= link_to 'GALLERY', '/#gallery', class:"white-link" %>&middot;
   				<%= link_to 'CONTACT', '/#contact', class:"white-link" %>&middot;
   				<%= link_to 'CONSTITUTION', '/static_pages/constitution.html', class:"white-link" %>&middot;
    		      		<%= link_to 'NEWS', '/static_pages/constitution.html', class:"white-link" %>&middot;
				<%= link_to 'EVENTS', '/posts', class:"white-link" %>
		   	</div>
 		 </p>

	</footer>

app/views/static_pages/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top navbar-sm">
    	<div class="container">
		<div class="navbar-header">
			<a class="navbar-brand" href="#">
				<%= image_tag "AITP_logo.png"%>
			</a>
		        <button type="button" class="navbar-toggle">
        			<span class="icon-bar"></span>
        			<span class="icon-bar"></span>
        			<span class="icon-bar"></span>                        
      			</button>	
		</div>
		<div class="navbar-collapse" id="myNavbar">
			<ul class="nav nav-justified">
				<li><%= link_to 'HOME', '/#home', class:"white-link" %></li>
				<li><%= link_to 'ABOUT US', '/#about', class:"white-link"  %></li>
				<li><%= link_to 'GALLERY', '/#gallery', class:"white-link"  %></li>
				<li><%= link_to 'VIDEOS', '/static_pages/videos.html', class:"white-link"  %></li>
				<li><%= link_to 'CONSTITUTION', '/static_pages/constitution.html', class:"white-link"  %></li>
				<li><%= link_to 'EVENTS', '/static_pages/events.html', class:"white-link"  %></li>
				<li><%= link_to 'REQUEST COMPUTER', '/requests/new', class:"white-link"  %></li>
			</ul>
		</div>
       	 </div>	
</nav>

app/views/static_pages/constitution.html.erb
<div id="const" class="const">
	<div class="container">
		<div class="row">
			<div class="col-lg-12 box">
				<h1 id="portfolio">ECSU Chapter Constitution</h1>
    			</div>
		</div>
		<div class="row">
        			<div class="col-lg-6 col-md-6 col-sm-6 box">
<br/><h3>Mission Statement</h3>
<br/>The ECSU Chapter for the Association of Information Technology Professionals is dedicated to providing opportunities to expand knowledge of Information Systems and Technologies. In addition professional development and scholastic excellence will be enhanced through cooperation with technology organizations, guest speakers, and business networking. 
<br/><h3>ARTICLE I - NAME</h3>
<br/>The name of this club shall be Association of Information Technologies Professionals, Eastern Connecticut State University Chapter (Club) 
<br/><h3>ARTICLE II - PURPOSE</h3>
<br/>It shall be the purpose of this organization to provide opportunities to expand knowledge of Information Systems and Technologies. In addition to encourage professional development and scholastic excellence, through cooperation with technology organizations, guest speakers, and business networking. 
<br/><h3>ARTICLE III - MEMBERSHIP </h3>
<br/>Section 1: This organization will be open to all students currently registered at Eastern Connecticut State University. 
<br/>Section 2: Anyone who attends two consecutive meetings will be considered a voting member of the Association of Information Technology Professionals, ECSU Chapter. However, anyone who has more than two consecutive inexcusable absences from regular meetings during the same semester will lose their voting privileges. 
<br/>Section 3: Any voting member unable to attend a meeting for an excusable reason may vote by absentee ballot. 
<br/>Section 4: Membership shall not be denied to any student because of race, religion, gender, color, ancestry, national origin, age, sexual orientation, disability or veteran status except as sanctioned by federal or state law. 
<br/><h3>ARTICLE IV - EXECUTIVE BOARD & OFFICERS</h3>
<br/>Section 1: The membership of the Executive Board shall consist of the President, Vice-President, Secretary, Treasurer, and Vice President of Public Relations. The Faculty Advisor shall serve as a non-voting ex-officio member of the Executive Board.
<br/>Section 2: The Executive Board shall have general supervision of the affairs of the organization between its regular business meetings and shall make policy recommendations to the organization. The Executive Board shall be subject to the rules of the organization and shall not act in conflict with actions taken by the organization.
<br/>Section 3: The Executive Board shall have the power to establish all standing and ad hoc committees of the organization. The President, with the advice of the Executive Board, shall have the power to appoint the chairpersons of all standing and ad hoc committees.
<br/>Section 4: The Executive Board shall meet as needed during the academic year. Meetings of the Executive Board shall be called by the President of the organization.
<br/>Section 5: A majority of the membership of the Executive Board shall constitute a quorum. All decisions made by the Executive Board shall be by a majority vote of the members present and voting.
<br/><h3>ARTICLE V - ENUMERATION OF POWERS AND DUTIES OF OFFICERS</h3>
<br/>Officers shall perform the duties prescribed by this constitution and by the parliamentary authority adopted by the organization. Duties shall include but shall not be limited to the following. 
<br/>Section 1: The President shall: 
<br/>
<br/>a. prepare the meeting agendas; 
<br/>
<br/>b. have the power to call executive board meetings and all regular and special meetings of the organization; 
<br/>
<br/>c. sign all official papers related to the club; 
<br/>
<br/>d. have the power, with the advice of the Executive Board, to appoint the chairpersons of all standing and ad hoc committees; 
<br/>
<br/>e. appoint a temporary secretary to take minutes when the secretary is absent; 
<br/>
<br/>f. act as the spokesperson for the organization;
<br/>
<br/>g. be an ex-officio member of all standing and ad hoc committees except the nominating committee. 
<br/>
<br/>Section 2: The Vice-President shall: 
<br/>
<br/>a. assist the president with responsibilities as needed; 
<br/>
<br/>b. carry out the duties of the president in the absence of the president; 
<br/>
<br/>c. automatically assume the powers and duties of the President if the President resigns, if the office of President becomes vacant, or if the President is impeached; 
<br/>
<br/>d. coordinate all social functions of the organization; 
<br/>
<br/>e. serve as coordinator of all standing and ad hoc committees; 
<br/>
<br/>f. be an ex-officio member of all standing and ad hoc committees. 
<br/>
<br/>Section 3: Treasurer shall: 
<br/>
<br/>a. expend funds as authorized by the membership of the organization as indicated in the organization’s minutes; 
<br/>
<br/>b. keep an accurate account of all receipts, membership dues, and expenditures of the organization; 
<br/>
<br/>c. submit financial reports; 
<br/>
<br/>
<br/>d. keep track of the club’s accounts, income, and expenditures; 
<br/>
<br/>e. give a Treasurer statement of balance at every meeting; 
<br/>
<br/>f. request financial assistance from the Student Government Association and Budget and Management Committee if needed; 
<br/>
<br/>g. be responsible for the organization complying with the Student Activities Business Procedures Manual.
<br/>Section 4: The Secretary shall: 
<br/>
<br/>a. keep a proper record of all activities of the club, including the minutes of every meeting; 
<br/>
<br/>b. take attendance at all business meetings of the organization; 
<br/>
<br/>c. prepare a roll call of members and call it when necessary; 
<br/>
<br/>d. authenticate by his/her signature all records and documents of the organization; 
<br/>
<br/>e. carry on the official correspondence of the club; which will be signed by the president; 
<br/>
<br/>f. give 72 hours of notice of all meetings; 
<br/>
<br/>g. distribute minutes within 48 hours of the meeting. 
<br/>
<br/>Section 5: The Vice President of Public Relations shall: 
<br/>
<br/>a. contact all guest speakers; 
<br/>
<br/>b. create and distribute press releases; 
<br/>
<br/>c. distribute and create event flyers as necessary; 
<br/>
<br/>d. administrate and maintain the AITP club web page. 
        			</div>
        			<div class="col-lg-6 col-md-6 col-sm-6 box">

<br/>
<br/><h3>ARTICLE VI - ADVISOR(S) </h3>
<br/>Section 1: The advisor shall be chosen by the membership at a duly constituted meeting of the organization by majority vote. 
<br/>
<br/>Section 2: The faculty advisor shall serve as a non-voting ex-officio member of the Executive Board. 
<br/>
<br/>Section 3: The advisors shall give advice for the better performance of the organization upon the membership’s request. 
<br/>
<br/>Section 4: The advisor shall meet his/her responsibilities to the organization as stated in written directives issued by the Student Activities Office and in the Club Advisor’s Operating Manual located on the Student Activities Website. 
<br/>
<br/>Section 5: The advisor shall serve at the discretion of the University. 
<br/>
<br/><h3>ARTICLE VII - NOMINATION AND ELECTION OF OFFICERS </h3>
<br/>Section 1: Elections shall be held for all offices, including those that are filled temporarily. 
<br/>
<br/>Section 2: Officers shall be elected for a term of one (1) year or until their successors are elected. They shall hold office until May when their successors shall assume office. 
<br/>
<br/>Section 3: Elections shall be held during the spring semester. Elections shall take place no earlier than March 15 and no later than April 30 of each year. 
<br/>
<br/>Section 4: Only active members shall be allowed to vote. Voting shall be by secret ballot unless there is only one candidate for an office in which case election may be by voice vote. 
<br/>
<br/>Section 5: Officers shall be elected by a majority of those members voting in the election. If no candidate receives a majority vote on the first ballot, additional ballots will be taken until a majority vote has been reached. 
<br/>
<br/>Section 6: Notification of elections must be given at least one week prior to voting. 
<br/>
<br/><h3>ARTICLE VIII - VACANCIES </h3>
<br/>Section 1: In the event of the vacancy of the office of president, the duties will be carried out by the vice-president. The office of vice-president will be carried out by the treasurer. The office of Treasurer will be carried out by the secretary. A new Secretary shall be elected. 
<br/>
<br/>Section 2: In the event of the vacancy of any other offices, the president will appoint a temporary officer and an election will be held as per the provision of Article VI Section 1.
<br/>
<br/><h3>ARTICLE IX - IMPEACHMENT AND/OR RECALL </h3>
<br/>
<br/>Section 1: Any officer is subject to impeachment and /or recall and removal from the office for failing to fulfill his/her constitutional responsibilities. 
<br/>
<br/>Section 2: An impeachment request must be given at least a week in advance of the actual impeachment voting. Both the request and the voting must take place during regular meetings. 
<br/>
<br/>Section 3: Upon conclusion of the discussion and arguments for and against impeaching the officer, a vote shall be taken. No officer shall be impeached except by a two-thirds (2/3) vote. Voting shall be by secret ballot. 
<br/>
<br/>Section 4: An officer who is impeached shall immediately relinquish his/her office but shall be allowed to maintain active membership in the organization unless his/her actions have brought discredit to the organization. 
<br/>
<br/>Section 5: If an officer is impeached, the organization shall fill the position following the procedures outlined under Vacancies.
<br/>
<br/><h3>ARTICLE X - MEETINGS</h3>
<br/>Section 1: Meetings of the organization shall be held at least twice a month during the academic year. There must be 48 hours of notice of all emergency meetings with the exception of Executive Board meetings. 
<br/>
<br/>Section 2: Quorum… a quorum shall be defined as 50% + 1 member of the club’s total voting membership. A quorum must be present for any action to take place by membership. 
<br/>
<br/>Section 3: A quorum shall be required to conduct any official business of the organization except to adjourn. 
<br/>
<br/>Section 4: If a tie vote occurs (i.e. 50/50), the president can cast the deciding vote. 
<br/>
<br/><h3>ARTICLE XI - AMENDMANTS </h3>
<br/>Section 1: Amendments to this constitution must be approved by a 2/3 majority of the voting membership present. 
<br/>
<br/>Section 2: Proposed amendments to the constitution shall be automatically tabled until the next scheduled meeting of the organization. 
<br/>
<br/>Section 3: Prior written notice of the proposed change(s) and the date of the meeting at which the proposed change(s) shall be voted on shall be provided to all members of the organization. 
<br/>
<br/>Section 4: The constitution may be amended at a duly constituted meeting of the organization by two-thirds (2/3) vote provided that prior notice has been given. 
<br/>
<br/><h3>ARTICLE XII - PARLIAMENTARY AUTHORITY </h3>
<br/>Robert’s Rule of Order, Newly Revised shall act as the Parliamentary authority for all meetings of the club. 
<br/>
<br/><h3>ARTICLE XIII - RATIFICATION </h3>
<br/>This constitution must be ratified by a majority vote at a regular meeting and approved by the Student Government Association Budget and Management Committee. 
<br/>
<br/><h3>ARTICLE XIV - DUES </h3>
<br/>This organization has the ability to asses the membership. Assessments shall be determined by a quorum of the membership at a regularly scheduled meeting.
<br/><h3>Competition Mission</h3> 
</br>We are the Association of Information Technology Professionals ECSU Student Chapter, we work to improve efficiencies and capabilities of local non-profit organizations. By the integrating of business processes with web-database technologies, we help local non-profit achieve their goals of assisting members of the Windham community. Our upcoming project plan is to implement a common web-database system to assist local non-profits in improving their efficiencies and the coordination of information and services to those in need, with the goal of enriching peoples’ lives and restoring them to being vital members of our community. 
AITP has competed 6 times nationally and are competing currently for the 7th time
Were 289 AITP chapters nationally, around 100 of them compete with the goal of competing nationally
        			</div>
      		</div><!-- end of row -->
	   	 </div>
	</div><!-- end of about -->

app/views/static_pages/events.html.erb
<br/>
<br/>
<div class="container">
	<div id='loading'>loading...</div>
	<div id='calendar'></div>
</div>

app/views/static_pages/videos.html.erb
	<div class="container">
		<div class="row">
			<div class="col-lg-12 box">
				<h1 id="portfolio">AITP Video Library</h1>
    			</div>
		</div>
			<div class="row">
				<div class="col-lg-6 col-md-6 col-sm-6 box" style="text-align:center;"><iframe width="85%" height="350px" src="https://www.youtube.com/embed/NLDA7YtWAnM?rel=0" frameborder="0" allowfullscreen></iframe>
        			</div>
				<div class="col-lg-6 col-md-6 col-sm-6 box" style="text-align:center;"><iframe width="85%" height="350px" src="https://www.youtube.com/embed/j_6I458ZZrM?rel=0" frameborder="0" allowfullscreen></iframe>

				</div>
			</div>
			<div class="row">
				<div class="col-lg-6 col-md-6 col-sm-6 box" style="text-align:center;"><iframe width="85%" height="350px" src="https://www.youtube.com/embed/YAWO4lnxbz4?rel=0" frameborder="0" allowfullscreen></iframe>
				</div>
				<div class="col-lg-6 col-md-6 col-sm-6 box" style="text-align:center;"><iframe width="85%" height="350px" src="https://www.youtube.com/embed/aB_vm-OFwwM?rel=0" frameborder="0" allowfullscreen></iframe>
				</div>
			</div>
		</div>